<?php 
	$title = "About Me";
	include("head.php"); 
?>
<div class="bg-content"> 
	<div id="content"> 
		<div class="container">
        	<div class="row">
        		<article class="span8">
					<h3>About Me</h3>        	
           			<p>Hello! As you may or may not know, my name is James Little. Ah, yes, has a nice ring to it. Anyways I am 23 years old and I am attending Texas Tech University. Blah, blah, blah.. Lets start from the beginning. I was born on the beautiful day of July, okay too far back. Fast forward, I am in 8th grade and about to finish the spring semester and getting ready for summer where I lounge around and do nothing all day and be your typical kid. </p><p>We have had a computer in our house for a couple of years at this point. I didn't understand much of it at the time. Computers seemed complicated, but I was curious on how they worked. I understood how to play video games and that was enough for me at the time. I am not sure how I got so interested into building a computer, but I figured I could do it. I remember looking up parts online and thinking "how on earth am I going to be able to afford this?" I was afraid of buying the wrong parts or not having all the cables or even not having a certain part that was common knowledge that you must have, but never mentioned. I did more than enough research to understand which parts I should buy and what exactly I needed to build her.</p>
                    
<p>After I accomplish my first task, building a computer, it was time to learn something new. At this point I am in high school, ah yeah, the awkward days. My first attempt at programming was writing batch scripts on my new windows machine. I don't really remember what they did, but I do remember writing a program called iPod Copier, when ran it would copy all of your music onto your computer into your music folder. Pretty pointless considering the filenames where encoded, however, I hated using iTunes. I posted it to Download.com. <br />
Moving forward, I played video games off and on, but I felt like I was wasting my time. I wanted to tackle a new task. I made a friend while playing online games; he was about my age and was making websites for some extra cash. I kind of saw him as mentor and decided to learn all the web technologies, Including PHP and MySQL. I would create these cruddy websites and ask him how they looked and he would let me know that they sucked. Thanks buddy! About this time I was in Computer Science UIL and Computer Applications UIL. Side note, I thought Computer Applications was really dumb and didn't care to put much effort into it. I mean, the whole goal was to focus on Microsoft Office Applications. They would tell you to make a database in MS Access, then make a report and pull it into excel then do this and do that and they would remove points if you had a type-o or things like that. They should have called it Microsoft Applications not Computer Applications. Anyways, there was about four of us in the Computer Science UIL team, I seem to be the best seeing how I enjoyed the crap out of programming. I didn't learn much from our "couch", but she tried. We even had the school make a Computer Science class, but I don' think that lasted. I did fairly well, but Lubbock High had the best Computer Science team considering they had a four year program and was turning out little Linus's over there.  Oh well.</p>
<p>Not very interested into sports, but wanted to do something, sitting on the couch with my dad watching the basketball games and him staring at his basketball bracket, curiously I asked, what's that? He told me he was running the bracket contest, but he had to manually look at everybody's bracket to count their points. I noticed an opportunity, I told him we could make a website that everybody could login to and the system would take care of counting points and everybody could view the standings and it would be a good o' time. Mind you, I was not very good at PHP or any C-based languages, but I figure you gotta jump out of the nest sometime. Unfortunately, I don't think I have the website saved anywhere, maybe I do. Not sure. </p><p>
After the learning process, I had to take down some tasks, like, how are these people going input their brackets? The problem was each round relied on the previous round, you know, a basketball bracket. I google'd other people's solutions; they all sucked.  One day, while not listening to the French teacher talk about some crap about yoga, I figured it out. Display a table and pull the initial values from the database, then save those selected values into a session array, then on the next round pull the session array values and continue until they have chosen the championship round. I figured it would be easier on the user if they did region by region instead of the whole bracket at once. 
Sounds pretty simple, but I was new to the game and it was giant feat for me and I was proud. Cool, so did random crap with my new found skills, nothing to write home about. Now we are into my senior year of high school, in that Computer Science class I helped create, we were learning Java. Neat. A new language. That's when I learned that most languages syntactically were very similar, I was naturally ahead of my class and usually finished my little projects fairly quickly. Oh did I mention I helped start a web design class too? Never mind with that, okay, not really start, but more like help inspired. </p>
<p>
All the seniors had to do a senior project, but it could be whatever you liked and you had to have mentor. I decided to do something computer related. I figured I would try to get my A+ certification, little did I know that was pretty hard to do. That was what senior project was for; it was to help open our young adolescent naive eyes to the real world. Oh well, I had fun reading my little A+ book, I was able to answer all the questions at the end of the chapter with no problems at all, I thought I was ready, I wasn't. Oh well, I didn't really care.</p><p>
While in high school I was able to join the Technical Honor Society, that was fun and pointless. I also made some great friends in the IT department, mainly because one was my mentor and the other one liked to talk to me when I was working during my office aid hours. He liked to take me on his IT adventures, I had a blast. He also taught me some things here and there, he also had a degree in Biology, what?</p>
<p>
Because of my IT friends, they hired me in the summer to help reset all of their computers throughout the campus. They didn't give us admin privileges, so we discovered a teacher's username and password and used that when we need to become admins or when we needed to, you know, play flash games while the computers where imaging. That was fun, until, my partners took down a whole hallway and almost giving the head IT guy a heart attack when they plugged a hub from the wall back to the wall. That kids is called a packet storm, or from what I am told. Also, this is when I learned that teachers have no idea how computers worked, even though they used them all the time. When they got back and discovered that their username was not their own but PaulD it was epic chaos! You see, the school used Novell and it would keep the last person's username in the username box and all you had to do was enter your password. Well, we used good o' PaulD as the username and that was fun changing them all back. </p>
<p>
Now we are into collage, yes! This is where men are made. I decided to take it slow and give a community college a try. There is nothing there but middle age women who giving it their second shot at life and soon to be college drop-outs because college is nothing more than party city. Okay, so there was a lot of dedicated fresh out of high school kids who were just as driven as I was. That is where I learned C++. I was also ahead of this class as well, was I really good at this or where all these kids really stupid? I guess it's not for everybody. I always finished my projects before the lab hour ended and would hang out talk to my fellow nerds about nerd stuff. The professor asked me to learn about enumeration and teach it to the class, I said sure why not. About this time, I applied for a web developer position. Around this time was when I really started to mess with Linux and using Linux as a web server.  Anyways, I got the position and it was a fun job. My first task was to fix some code issues from the previous developer, the code sucked. I ended up scraping it and rewriting it, then asked me to implement some new features. The also would have me fix some of their computers or printers. The job was really fun. I also was taking a pre design template from the designer and turning it into a website. Then one day the account, I think that's what she did, told me, "Oh, hey don't come in Monday, we won't be here, we are moving the operation to Spearman." Uhh, what? Whatever.
Moving on to Texas Tech, the big boy school. I didn't learn much my first year or two. I had to take an intro programming class, again, and winded up teach the lab again. And that leaves us where I am at today.</p><p>
Through my journey, I have learned C++, PHP, Java, HTML, CSS, MySQL, Linux systems, basic networking, general computing skills, building computers, diagnosing computers. It's been fun so far, I still have a long way to go, but I am having fun doing it and I won't stop at nothing to achieve a degree in computer science, it's nothing less than a passion. Also, I do realize there is an outside world, I am decently social nowadays. 
</p>
				</article>
                <article class="span4">
              		<h3>&zwnj;</h3>
                    <img src="img/me.png" alt="Me!"  />
            	</article>
             </div>
		</div>
	</div> 
</div> 
<?php include("foot.php"); ?>